### PR TITLE
Fix python3 seek

### PR DESCRIPTION
**Pull request by dedekind**

### CODE REVIEW

**Comment by smcv** [comment]
Yes, this is a more elegant version of what I had in mind when reviewing #42.

**Comment by smcv** [comment]
> The urllib2 file-like objects emulated seek()

I think that's a bit misleading: they don't have a seek() method at all, and TransRead responds to that by emulating it. The difference in Python 3 is that they do have a seek() method, but it fails.

**Comment by dedekind** [comment]
> I think that's a bit misleading: they don't have a seek() method at all, and TransRead responds to that by emulating it. The difference in Python 3 is that they do have a seek() method, but it fails.

Right, thanks, I'll amend the message.

**Comment by smcv** [comment]
> I am not sure what is the best practice of amending the commit message in github, I ended up with oldschool '--amend'.

Do the `--amend` locally, and force-push the branch (if you use the same branch name it will automatically update the pull request). Or at least, that's what I do!

**Comment by smcv** [comment]
The combination of this and #46 works for me when applied as patches to Debian's bmaptool (which uses Python 3):

```
webroot$ truncate -s100M filesystem.img
webroot$ mkfs.vfat filesystem.img
webroot$ bmaptool create filesystem.img > filesystem.img.bmap

elsewhere$ bmaptool copy http://localhost/.../filesystem.img filesystem.out
elsewhere$ diff -s /...webroot.../filesystem.img filesystem.out
```

**Comment by ribalda** [comment]
Looks good to me. I will try both patches tomorrow in the office.

Thanks for your fast response fixing this

**Pull request merged**
